### ISSUE TITLE
feat:Proper config handling for ocm token

### ISSUE THREAD

**Issue by rafael-azevedo** [geowa4/servicelogger#10]
Proper config handling for ocm token so that we do not have to pass it in as flags

**Comment by rafael-azevedo** [comment]
reduce to one flag that can take the output of `ocm token`

**Comment by geowa4** [comment]
I demonstrate this in https://github.com/geowa4/servicelogger/pull/9/files#diff-83e5cc2dfa3554ded718960969e8a817d6791f7e3c9c769a1136e6a0a3f94820R48.
